---
board:
  rows: 10
  columns: 10
  margin: 4
  size: 600

pieces:
  data_file: "assets/units.json"
  counts:
    # Piece Strength: Count of Pieces
    0: 1
    1: 1
    2: 8
    3: 5
    4: 4
    5: 4
    6: 4
    7: 3
    8: 2
    9: 1
    10: 1
    11: 6

sprites:
  data_file: "assets/sprites.json"

presets:
  count: 3
  data_file: "assets/presets.json"

opponent:
  preset: -1

window:
  title: Stratego
  height: 720
  width: 1024

debug: true
